dictionaries = ["en_us"]
words = [
    "besselj",
    "bessels",
    "bmatrix",
    "cachegrind",
    "callgrind",
    "codebook",
    "dgh",
    "doi",
    "electrodynamic",
    "frac",
    "hdf",
    "iman's",
    "infty",
    "katex",
    "lerche",
    "linearize",
    "memcheck",
    "metapackage",
    "newberger",
    "optim",
    "perp",
    "plasmas",
    "raphson",
    "rightarrow",
    "valgrind",
    "vlasov",
    "warpxm",
    "wavenumber",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    "assets/**/*",
    "**/*.json",
    ".git/**/*",
    "themes/**/*",
]
